name: final_career_coaching
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # google_fonts: ^4.0.3
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.7
  intl: ^0.18.1
  table_calendar: ^3.0.0
  carousel_slider: ^4.2.0
  unicons: ^2.0.0
  image_picker: ^0.8.7+4
  image_cropper: ^9.0.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.11.0
  fl_chart: ^0.69.2
  http: ^1.2.2
  data_table_2: ^2.5.18
  file_picker: ^8.1.6
  shared_preferences: ^2.2.2
  syncfusion_flutter_xlsio: ^29.1.35
  path_provider: ^2.1.1
  open_file: ^3.3.3
  flutter_cache_manager: ^3.4.1
  syncfusion_flutter_charts: ^29.1.35
  syncfusion_flutter_core: ^29.1.35
  permission_handler: ^10.4.0
  csv: ^5.0.1
  sqflite: ^2.2.8+4
  universal_io: ^2.0.4
  cross_file: ^0.3.3
  flutter_downloader: ^1.10.2
  dio: ^5.3.2
  download: ^1.0.0  # Alternative for web downloads
  file_saver: ^0.2.14
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: 0.4.5+4
  device_info_plus: ^9.0.3
  archive: ^3.3.0
  cached_network_image: ^3.3.0
  provider: ^6.0.5
  get: ^4.6.5  # For GetX state management
  google_fonts: ^6.2.1  # For custom fonts

  path: any
  http_parser: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/